# REVIVAL_BATTLE_BRIDGE (generated by out/tools/export_battle_bridge.py)
# 来源: GMA-Revive-Server turnclock.client_bridge_source()
# bridge_version=1 bridge_revision=15 hotfix_index=2026100816
# sha256=77ef4867326027bae10a3951fccb86e2499e839675ecf322dd6a17dfb5715e5a

def _install_revival_battle_bridge():
    import sys
    import time
    import gworld
    import common_const
    from battle_logic import client_battle
    from battle_logic.controlers import server as server_control
    from guis.battle import battle_mode
    shadow = client_battle.shadow_battle
    local = client_battle.local_battle
    mode = battle_mode.battle_mode
    if (getattr(shadow, '_revival_bridge_version', 0) == 15
            and getattr(shadow, '_revival_result_uuid_revision', 0) == 2):
        return

    def skill_target_hooks(process_command, skill_result, report):
        # Keep this function self-contained and Python 2 compatible for hotfix embedding.
        def process(self, user):
            previous = getattr(self, '_revival_skill_cast', None)
            context = None
            try:
                name, args = user.command
                if name in ('use_skill', 'use_support_skill', 'use_extra_support_skill',
                            'charm_use_skill', 'taunt_use_skill'):
                    self._revival_cast_sequence = getattr(self, '_revival_cast_sequence', 0) + 1
                    context = {'cast_id': self._revival_cast_sequence, 'eid': str(user.eid),
                               'skill_id': args[0], 'target_eids': [], 'target_roles': {}}
            except Exception:
                pass
            self._revival_skill_cast = context
            try:
                result = process_command(self, user)
            finally:
                self._revival_skill_cast = previous
            if context is not None and not context.get('incomplete'):
                try:
                    report(self, 'skill_targets', context)
                except Exception:
                    pass
            return result

        def resolve(self, effect_struct, effect_play, result_struct):
            context = getattr(self, '_revival_skill_cast', None)
            target_id = role = None
            try:
                # The native result is created after range/random/target confirmation.
                # Exclude counterattacks and passive skills executed inside this cast.
                if (context is not None and str(result_struct.user.eid) == context['eid']
                        and result_struct.skill is not None
                        and result_struct.skill.skill_id == context['skill_id']):
                    target_id = str(result_struct.target.eid)
                    role = int(result_struct.target.get_role_id())
            except Exception:
                if context is not None:
                    context['incomplete'] = True
            result = skill_result(self, effect_struct, effect_play, result_struct)
            if target_id is not None and target_id not in context['target_eids']:
                context['target_eids'].append(target_id)
                context['target_roles'][target_id] = role
            return result

        return process, resolve


    def function(method):
        return getattr(method, 'im_func', method)

    originals = getattr(shadow, '_revival_bridge_originals', {})

    def original(name, captured):
        method = function(getattr(shadow, name))
        if name in originals:
            return originals[name]
        # Revision 1 stored originals in closures; unwrap before upgrading.
        code = getattr(method, 'func_code', getattr(method, '__code__', None))
        closure = getattr(method, 'func_closure', getattr(method, '__closure__', None))
        if code is not None and closure:
            for freevar, cell in zip(code.co_freevars, closure):
                if freevar == captured:
                    return cell.cell_contents
        return method

    def ident(value):
        return str(value)

    def state(battle):
        units = []
        for eid, info in battle.entity_infos.items():
            coord = info.get_attr('hex_coord')
            if not isinstance(coord, (list, tuple)) or len(coord) != 3:
                continue
            camp = info.get_camp_id()
            native_type = getattr(info, 'type', None)
            is_field = native_type == common_const.INFO_TYPE_MAGIC_FIELD
            kind = 'field' if is_field else ('support' if info.is_support() else ('ally' if camp == 1 else ('enemy' if camp == 2 else 'neutral')))
            unit = {'eid': str(eid), 'role': int(info.get_role_id()), 'kind': kind,
                    'hex': list(coord), 'alive': not info.is_dead()}
            if native_type is not None:
                unit['native_type'] = native_type
            if is_field:
                unit['camp'] = int(camp)
                for key in ('mf_id', 'mf_radius'):
                    value = info.get_attr(key)
                    if isinstance(value, (int, float)):
                        unit[key] = value
            for key in ('hp', 'max_hp', 'ap'):
                value = info.get_attr(key)
                if isinstance(value, (int, float)):
                    unit[key] = value
            units.append(unit)
        return {'units': units}

    def emit(battle, kind, data):
        # 原生结束链会先清空 battle.id，随后才调用 notify_battle_finish。
        # result 必须沿用 prepare/ready 阶段冻结的 UUID，不能把字符串 None
        # 上报给服务端，否则结算会因归属不符被拒绝。
        current_id = getattr(battle, 'id', None)
        battle_id = ident(current_id)
        if current_id is None and kind == 'result':
            battle_id = getattr(battle, '_revival_event_uuid', None)
            if not battle_id:
                raise ValueError('battle result uuid missing')
        if getattr(battle, '_revival_event_uuid', None) != battle_id:
            battle._revival_event_uuid = battle_id
            battle._revival_event_sequence = 0
            battle._revival_event_begin = time.time()
        sequence = battle._revival_event_sequence + 1
        payload = {'battle_uuid': battle_id, 'sequence': sequence,
                   't': max(0.0, time.time() - battle._revival_event_begin), 'kind': kind, 'data': data}
        gworld.get_player().server_proxy.do_command('__battle_event__', [payload])
        battle._revival_event_sequence = sequence

    def report(battle, kind, data=None, include_state=False):
        # Recording must never interrupt a native play/round callback.
        try:
            payload = state(battle) if include_state else {}
            payload.update(data or {})
            emit(battle, kind, payload)
            return True
        except Exception as error:
            print('REVIVAL_BATTLE_REPORT_ERROR %s: %s' % (kind, error))
            return False

    native = {}
    for name in ('start_next_round', 'round_end', 'server_round_end', 'delay_call_round_end',
                 'server_after_pre_play', 'continue_old_round', 'wait_for_master_input',
                 'on_player_input', 'on_master_input', 'do_uninterrupted_action',
                 'do_master_action', 'client_trigger_sequence_action',
                 'run_battle_storyline_end', 'battle_guide_end', 'battle_end',
                 'change_auto_state'):
        native[name] = function(getattr(local, name))
    old_prepare = original('prepare', 'old_prepare')
    old_check_auto_fighting = original('check_auto_battle_fighting', 'old_check_auto_fighting')
    old_fighting = original('battle_fighting', 'old_fighting')
    old_wait = original('wait_for_player_input', 'old_wait')
    old_log_command = original('log_command', 'old_log_command')
    old_process_command = original('process_command', 'old_process_command')
    old_skill_result = original('skill_result', 'old_skill_result')
    old_start_action = original('real_start_action', 'old_start_action')
    old_trigger_end = original('trigger_battle_end', 'old_trigger_end')
    old_dispatch_plays = original('dispatch_plays', 'old_dispatch_plays')
    old_end_notice = original('battle_end_notice', 'old_end_notice')
    old_real_story = original('real_run_battle_storyline', 'old_real_story')
    old_press_auto = function(getattr(mode, '_revival_press_auto_original',
                                     mode.press_auto))
    validate_command = function(server_control.controler.do_command)

    def prepare(self, *args, **kwargs):
        # Native preparation can update the mode UI before the handshake.
        self._revival_ready = False
        self._revival_preparing = True
        self._revival_deferred_auto_fighting = False
        try:
            result = old_prepare(self, *args, **kwargs)
        except:
            self._revival_deferred_auto_fighting = False
            raise
        finally:
            self._revival_preparing = False
        self._revival_started = False
        self._revival_result_sent = False
        # 原生结束链在 notify_battle_finish 前会 clear_battle；玩家实体也可能
        # 已切换。胜负归属必须使用 prepare 阶段冻结的玩家 eid。
        self._revival_player_eid = ident(gworld.get_player().eid)
        self._revival_finished_tasks = None
        self._revival_end_scheduled = False
        self._revival_play_tokens = set()
        self._revival_wait_end = None
        self._revival_ready = report(self, 'ready', {'version': 1})
        deferred = self._revival_deferred_auto_fighting
        self._revival_deferred_auto_fighting = False
        if deferred and self._revival_ready:
            old_check_auto_fighting(self)
        return result

    def check_auto_battle_fighting(self):
        # Reusing a scene can finish its load inside native prepare. Defer
        # the request until ready is sent, before Avatar sets battle_fight_flag.
        if getattr(self, '_revival_preparing', False):
            self._revival_deferred_auto_fighting = True
            return
        return old_check_auto_fighting(self)

    def change_auto_state(self, state):
        result = native['change_auto_state'](self, state)
        # Report the accepted native state, including unlock checks, only for
        # the prepared current battle. Preference restoration stays silent.
        try:
            caller = sys._getframe(1).f_code
            # Guess-PVP's native confirmation callback runs after press_auto
            # returns. Cancelling is still an explicit user choice.
            user_change = (getattr(self, '_revival_user_auto_change', False)
                or (caller.co_name == 'cancel_change' and caller.co_filename.replace('/', '\\')
                    .endswith('guis\\battle\\battle_mode.py')))
            if (getattr(self, '_revival_ready', False)
                    and user_change
                    and not getattr(self, '_revival_restoring_preferences', False)
                    and not getattr(self, '_revival_result_sent', False)
                    and self.bid is not None and gworld.get_battle() is self
                    and getattr(self, '_revival_event_uuid', None) == ident(self.id)):
                report(self, 'settings', {
                    'auto_battle': gworld.get_player().eid in self.auto_battle_set})
        except Exception as error:
            print('REVIVAL_BATTLE_REPORT_ERROR settings: %s' % error)
        return result

    def set_battle_preferences(self, speed, automatic):
        restoring = getattr(self, '_revival_restoring_preferences', False)
        self._revival_restoring_preferences = True
        try:
            self.set_battle_speed(speed)
            return native['change_auto_state'](self, automatic)
        finally:
            self._revival_restoring_preferences = restoring

    def press_auto(self, *args, **kwargs):
        # Persist explicit button choices. Native battle rules also change
        # automatic mode, but those temporary changes must stay battle-local.
        battle = gworld.get_battle()
        if battle is None:
            return old_press_auto(self, *args, **kwargs)
        user_change = getattr(battle, '_revival_user_auto_change', False)
        battle._revival_user_auto_change = True
        try:
            return old_press_auto(self, *args, **kwargs)
        finally:
            battle._revival_user_auto_change = user_change

    def fighting(self, *args, **kwargs):
        result = old_fighting(self, *args, **kwargs)
        if not self._revival_started:
            self._revival_started = True
            report(self, 'started', include_state=True)
        return result

    def after_pre_play(self, user, preplay_duration, play_delay):
        report(self, 'turn', {'eid': str(user.eid)}, include_state=True)
        return native['server_after_pre_play'](self, user, preplay_duration, play_delay)

    def wait_for_input(self, info):
        result = old_wait(self, info)
        report(self, 'input', {'eid': str(info.eid)}, include_state=True)
        return result

    def log_command(self, user):
        result = old_log_command(self, user)
        context = getattr(self, '_revival_skill_cast', None)
        report(self, 'command', {'eid': str(user.eid), 'command': user.command,
                                'cast_id': context['cast_id'] if context else None})
        return result

    def round_end(self, eid):
        report(self, 'round_end', {'eid': None if eid is None else str(eid)}, include_state=True)
        return native['round_end'](self, eid)

    def finish_instance_sequence(self, method, *args):
        # 原生 server_controler 在实例剧情/战斗引导结束后只上报服务端，
        # EVENT_ACTION_INSTANCE 即使本地序列已空也刻意不调用 event_all_triggered。
        # 当前桥由客户端原生引擎权威推进，必须在同一演出真正结束的回调点
        # 接续保存的 round_end continuation；不能用定时器猜测或跳过演出。
        result = native[method](self, *args)
        activate_type = args[-1] if args else None
        if (activate_type == common_const.EVENT_ACTION_INSTANCE
                and not self.sequence_actions
                and self.wait_event_signal is not None):
            print('REVIVAL_BATTLE_INSTANCE_CONTINUE %s' % method)
            self.event_all_triggered()
        return result

    def trigger_sequence_actions(self):
        # shadow_battle 原本由服务端控制器驱动；local_battle 的同名方法是空实现。
        # start_next_round 必须在这里执行剩余序列事件，事件管理器随后会通过
        # event_all_triggered 释放 round_end 保存的 continuation。
        return self.trigger_all_sequence_actions()

    def storyline_end(self, story_name, activate_type):
        return finish_instance_sequence(self, 'run_battle_storyline_end', story_name, activate_type)

    def guide_end(self, activate_type):
        return finish_instance_sequence(self, 'battle_guide_end', activate_type)

    def real_story(self, *args, **kwargs):
        # battle_mgr.real_run_battle_storyline 对带 activate_type 的实例剧情
        # 不调用 run_battle_storyline_end；原厂等待服务端权威继续。把接续挂到
        # 真正的 story end_callback 后一帧，确保模型/UI 清理完成再释放 round_end。
        values = list(args)
        old_extra = values[5] if len(values) > 5 else kwargs.get('extra_callback')
        def after_story():
            if old_extra is not None:
                old_extra()
            def resume():
                if (not self.storyline_contents
                        and not self.sequence_actions
                        and self.wait_event_signal is not None):
                    print('REVIVAL_BATTLE_STORY_CONTINUE')
                    self.event_all_triggered()
            self.add_callback(0, resume)
        if len(values) > 5:
            values[5] = after_story
        else:
            kwargs['extra_callback'] = after_story
        return old_real_story(self, *values, **kwargs)

    def start_action(self, info, delay, play_delay):
        # A scripted victory can arrive while after_pre_play is processing
        # events. Its saved continuation must finish instead of opening a turn.
        if self.winner_eid_list is not None:
            return self.trigger_battle_end(max(0, delay + play_delay), info)
        return old_start_action(self, info, delay, play_delay)

    def trigger_end(self, delay, info):
        if self.winner_eid_list is None:
            return old_trigger_end(self, delay, info)
        if getattr(self, '_revival_end_scheduled', False):
            return
        self._revival_end_scheduled = True
        def finish():
            try:
                return old_trigger_end(self, delay, info)
            except Exception:
                self._revival_end_scheduled = False
                raise
        if getattr(self, '_revival_play_tokens', None):
            self._revival_wait_end = finish
            return
        return finish()

    def dispatch_plays(self, plays):
        # The renderer also waits p.delay; calc_plays_time excludes that delay.
        # Capture it before do_play can consume/reset a play's delay field.
        play_duration = sum(max(0, p.get_action_time() + p.delay) for p in plays)
        duration = old_dispatch_plays(self, plays)
        if play_duration > 0:
            tokens = getattr(self, '_revival_play_tokens', None)
            if tokens is None:
                tokens = self._revival_play_tokens = set()
            token = object()
            tokens.add(token)
            def played():
                # A callback left over from a prior battle must not finish a new one.
                if getattr(self, '_revival_play_tokens', None) is not tokens:
                    return
                tokens.discard(token)
                if not tokens:
                    finish = getattr(self, '_revival_wait_end', None)
                    self._revival_wait_end = None
                    if finish is not None and self.bid is not None:
                        finish()
            self.add_callback(play_duration, played)
        return duration

    def end_notice(self, winners, action_counter):
        result = old_end_notice(self, winners, action_counter)
        battle_id = self.id
        tokens = getattr(self, '_revival_play_tokens', None)
        if tokens is None:
            tokens = self._revival_play_tokens = set()
        print('REVIVAL_BATTLE_END_NOTICE %s action=%s plays=%s' %
              (ident(battle_id), action_counter, len(tokens or ())))
        def finish_notice():
            if (self.id != battle_id or self.bid is None
                    or getattr(self, '_revival_play_tokens', None) is not tokens
                    or getattr(self, '_revival_result_sent', False)):
                return
            if self.winner_eid_list is not None:
                infos = self.action_list
                self.trigger_battle_end(0, infos[0] if infos else None)
        # Victory may be calculated inside compose_play, before dispatch_plays.
        # Let that calculation finish, then wait for every native play duration.
        self.add_callback(0, finish_notice)
        return result

    def do_command(self, command, args):
        # RPC arrays decode as lists; the native hex map uses tuple keys.
        # Both move_to and cell-target use_skill carry the coordinate last,
        # including use_skill requests prefixed with a ck_* counter tag.
        args = list(args)
        if command in ('move_to', 'use_skill') and args and isinstance(args[-1], list):
            args[-1] = tuple(args[-1])
        return validate_command(self, gworld.get_player().eid, command, *args)

    def notify_finish(self):
        winners = self.winner_eid_list
        if winners is None or self._revival_result_sent:
            return
        if self._revival_finished_tasks is None:
            try:
                tasks = self.get_tower_task_statistics()
                if not isinstance(tasks, (list, tuple)):
                    raise ValueError('native task statistics must be a list')
                unique = []
                for task in tasks:
                    if isinstance(task, bool) or not isinstance(task, int) or task <= 0:
                        raise ValueError('invalid native task id')
                    if task not in unique:
                        unique.append(task)
                self._revival_finished_tasks = unique
            except Exception as error:
                print('REVIVAL_BATTLE_TASK_ERROR %s' % error)
                return
        player_eid = getattr(self, '_revival_player_eid', None)
        if not player_eid:
            raise ValueError('battle result player eid missing')
        winner_eids = [ident(value) for value in winners]
        self._revival_result_sent = report(self, 'result',
            {'winner_eids': winner_eids,
             'player_eid': player_eid,
             'outcome': 'win' if player_eid in winner_eids else 'loss',
             'finished_task_list': list(self._revival_finished_tasks)}, include_state=True)

    for name, method in native.items():
        setattr(shadow, name, method)
    shadow.client_trigger_sequence_action = trigger_sequence_actions
    shadow.prepare = prepare
    shadow.check_auto_battle_fighting = check_auto_battle_fighting
    shadow.battle_fighting = fighting
    shadow.server_after_pre_play = after_pre_play
    shadow.wait_for_player_input = wait_for_input
    shadow.log_command = log_command
    shadow.process_command, shadow.skill_result = skill_target_hooks(
        old_process_command, old_skill_result, report)
    shadow.round_end = round_end
    shadow.run_battle_storyline_end = storyline_end
    shadow.battle_guide_end = guide_end
    shadow.real_run_battle_storyline = real_story
    shadow.real_start_action = start_action
    shadow.trigger_battle_end = trigger_end
    shadow.dispatch_plays = dispatch_plays
    shadow.battle_end_notice = end_notice
    shadow.change_auto_state = change_auto_state
    shadow.revival_set_battle_preferences = set_battle_preferences
    mode.press_auto = press_auto
    mode._revival_press_auto_original = old_press_auto
    shadow.revival_do_command = do_command
    shadow.notify_battle_finish = notify_finish
    shadow._revival_bridge_originals = {'prepare': old_prepare,
        'check_auto_battle_fighting': old_check_auto_fighting, 'battle_fighting': old_fighting,
        'wait_for_player_input': old_wait, 'log_command': old_log_command,
        'process_command': old_process_command, 'skill_result': old_skill_result,
        'real_start_action': old_start_action, 'trigger_battle_end': old_trigger_end,
        'dispatch_plays': old_dispatch_plays, 'battle_end_notice': old_end_notice,
        'real_run_battle_storyline': old_real_story}
    shadow._revival_bridge_version = 15
    shadow._revival_result_uuid_revision = 2

def _revival_start_battle_bridge(install):
    def attempt():
        try:
            install()
            print('REVIVAL_BATTLE_BRIDGE_READY 1 revision=15 result_identity=2 sequence_continue=1')
        except Exception as error:
            print('REVIVAL_BATTLE_BRIDGE_WAIT %s' % error)
            try:
                import game3d
                game3d.delay_exec(1500, attempt)
            except Exception as retry_error:
                print('REVIVAL_BATTLE_BRIDGE_RETRY_ERROR %s' % retry_error)
    attempt()

_revival_start_battle_bridge(_install_revival_battle_bridge)
