# HS_NATIVE_PVP_AUTHORITY
[Service]
Environment=HS_NATIVE_PVP_PYTHON=/opt/hs-server/native-pvp/current/python2/run-python2
Environment=HS_NATIVE_PVP_WORKER=/opt/hs-server/native-pvp/current/workspace/internal/nativepvp/battle_native_worker.py
Environment=HS_NATIVE_PVP_DIRECTORY=/opt/hs-server/native-pvp/current/workspace/internal/nativepvp/runtime/native_engine
Environment=HS_NATIVE_PVP_RESOURCE_SHA256=bed95c22e6e6adf4ccf01cabb5156b4888ccc5744f0e192d24501e6df3c19ef3
